### ISSUE TITLE
Field Guide notebook resize feature

### ISSUE THREAD

**Issue by nynnejc** [Jiskahuizing/torn-tracks#38]
i flexbox !

**Comment by Jiskahuizing** [comment]
Images of notebook for resize feature.

![Notebook_rectangle01](https://user-images.githubusercontent.com/32093657/61871996-82188e00-aee2-11e9-8ec7-28ecd6036bd9.jpg)
![Notebook_rectangle01](https://user-images.githubusercontent.com/32093657/61871997-82b12480-aee2-11e9-94e4-80fdcebb9934.png)
![Notebook_square01](https://user-images.githubusercontent.com/32093657/61871998-82b12480-aee2-11e9-8d20-c916250aaa17.jpg)
![Notebook_square01](https://user-images.githubusercontent.com/32093657/61872000-82b12480-aee2-11e9-9984-77f525c39099.png)
